/** Design System — Storybook stories (7 story groups) */
import React from 'react';
import { ScrollView, View, Text } from 'react-native';

// ── Button Stories ──
export function ButtonStories() { return (<ScrollView style={{ padding: 20, backgroundColor: '#0A0A0A' }}><Text style={{ color: '#FFF', fontSize: 18, fontWeight: '700', marginBottom: 16 }}>Button Variants</Text>{['primary', 'secondary', 'ghost', 'outline', 'danger', 'success'].map(v => <View key={v} style={{ marginBottom: 12, height: 48, backgroundColor: '#1A1A2E', borderRadius: 12, alignItems: 'center', justifyContent: 'center' }}><Text style={{ color: '#9CA3AF' }}>{v} Button</Text></View>)}<Text style={{ color: '#FFF', fontSize: 18, fontWeight: '700', marginBottom: 16, marginTop: 24 }}>Button Sizes</Text>{['sm', 'md', 'lg'].map(s => <View key={s} style={{ marginBottom: 8, height: s === 'lg' ? 56 : s === 'sm' ? 36 : 48, backgroundColor: '#1A1A2E', borderRadius: 12, alignItems: 'center', justifyContent: 'center' }}><Text style={{ color: '#9CA3AF' }}>Size {s.toUpperCase()}</Text></View>)}</ScrollView>); }

// ── Card Stories ──
export function CardStories() { return (<ScrollView style={{ padding: 20, backgroundColor: '#0A0A0A' }}><Text style={{ color: '#FFF', fontSize: 18, fontWeight: '700', marginBottom: 16 }}>Cards</Text>{['elevated', 'outlined'].map(v => <View key={v} style={{ marginBottom: 16, padding: 24, backgroundColor: '#1A1A2E', borderRadius: 16, borderWidth: v === 'outlined' ? 1 : 0, borderColor: '#2A2A3E' }}><Text style={{ color: '#FFF', fontSize: 16, fontWeight: '600' }}>{v}</Text><Text style={{ color: '#9CA3AF', fontSize: 14, marginTop: 4 }}>Card content</Text></View>)}</ScrollView>); }

// ── Input Stories ──
export function InputStories() { return (<ScrollView style={{ padding: 20, backgroundColor: '#0A0A0A' }}><Text style={{ color: '#FFF', fontSize: 18, fontWeight: '700', marginBottom: 16 }}>Text Fields</Text><View style={{ marginBottom: 16 }}><Text style={{ color: '#9CA3AF', fontSize: 12, marginBottom: 6 }}>With label</Text><View style={{ flexDirection: 'row', alignItems: 'center', borderWidth: 1.5, borderColor: '#2A2A3E', borderRadius: 12, paddingHorizontal: 14, height: 48, backgroundColor: '#222240' }}><Text style={{ color: '#6B7280' }}>Placeholder text</Text></View></View><View style={{ marginBottom: 16 }}><Text style={{ color: '#9CA3AF', fontSize: 12, marginBottom: 6 }}>With error</Text><View style={{ flexDirection: 'row', alignItems: 'center', borderWidth: 1.5, borderColor: '#EF4444', borderRadius: 12, paddingHorizontal: 14, height: 48, backgroundColor: '#222240' }}><Text style={{ color: '#6B7280' }}>Invalid input</Text></View><Text style={{ color: '#EF4444', fontSize: 12, marginTop: 4 }}>This field is required</Text></View></ScrollView>); }

// ── Dialog Stories ──
export function DialogStories() { return (<ScrollView style={{ padding: 20, backgroundColor: '#0A0A0A' }}><Text style={{ color: '#FFF', fontSize: 18, fontWeight: '700', marginBottom: 16 }}>Dialogs</Text><View style={{ backgroundColor: '#1A1A2E', borderRadius: 16, padding: 32, marginBottom: 16 }}><Text style={{ color: '#FFF', fontSize: 18, fontWeight: '700', marginBottom: 8 }}>Confirmation</Text><Text style={{ color: '#9CA3AF', fontSize: 14, marginBottom: 20 }}>Are you sure you want to continue?</Text><View style={{ flexDirection: 'row', gap: 12, justifyContent: 'flex-end' }}><View style={{ paddingVertical: 12, paddingHorizontal: 24, backgroundColor: '#222240', borderRadius: 12 }}><Text style={{ color: '#FFF' }}>Cancel</Text></View><View style={{ paddingVertical: 12, paddingHorizontal: 24, backgroundColor: '#3B82F6', borderRadius: 12 }}><Text style={{ color: '#FFF' }}>Confirm</Text></View></View></View><View style={{ backgroundColor: '#1A1A2E', borderRadius: 16, padding: 32 }}><Text style={{ color: '#FFF', fontSize: 18, fontWeight: '700', marginBottom: 8 }}>Danger</Text><Text style={{ color: '#9CA3AF', fontSize: 14, marginBottom: 20 }}>This action is permanent and cannot be undone.</Text><View style={{ flexDirection: 'row', gap: 12, justifyContent: 'flex-end' }}><View style={{ paddingVertical: 12, paddingHorizontal: 24, backgroundColor: '#222240', borderRadius: 12 }}><Text style={{ color: '#FFF' }}>Cancel</Text></View><View style={{ paddingVertical: 12, paddingHorizontal: 24, backgroundColor: '#DC2626', borderRadius: 12 }}><Text style={{ color: '#FFF' }}>Delete</Text></View></View></View></ScrollView>); }

// ── Skeleton Stories ──
export function SkeletonStories() { return (<ScrollView style={{ padding: 20, backgroundColor: '#0A0A0A' }}><Text style={{ color: '#FFF', fontSize: 18, fontWeight: '700', marginBottom: 16 }}>Loading States</Text>{[1,2,3].map(i => <View key={i} style={{ marginBottom: 16, padding: 24, gap: 10 }}><View style={{ height: 14, backgroundColor: '#1A1A2E', borderRadius: 8 }} /><View style={{ height: 14, backgroundColor: '#1A1A2E', borderRadius: 8, width: '60%' }} /><View style={{ height: 14, backgroundColor: '#1A1A2E', borderRadius: 8 }} /></View>)}</ScrollView>); }

// ── State Stories ──
export function StateStories() { return (<ScrollView style={{ padding: 20, backgroundColor: '#0A0A0A' }}><Text style={{ color: '#FFF', fontSize: 18, fontWeight: '700', marginBottom: 16 }}>Empty & Error</Text><View style={{ alignItems: 'center', paddingVertical: 60 }}><Text style={{ fontSize: 48 }}>🔍</Text><Text style={{ color: '#9CA3AF', fontSize: 14, marginTop: 12, textAlign: 'center' }}>No results found</Text><View style={{ marginTop: 20, paddingVertical: 12, paddingHorizontal: 24, backgroundColor: '#3B82F6', borderRadius: 12 }}><Text style={{ color: '#FFF', fontWeight: '600' }}>Clear filters</Text></View></View><View style={{ alignItems: 'center', paddingVertical: 60 }}><Text style={{ fontSize: 48 }}>⚠️</Text><Text style={{ color: '#9CA3AF', fontSize: 14, marginTop: 12, textAlign: 'center' }}>Something went wrong</Text><View style={{ marginTop: 20, paddingVertical: 12, paddingHorizontal: 24, backgroundColor: '#3B82F6', borderRadius: 12 }}><Text style={{ color: '#FFF', fontWeight: '600' }}>Retry</Text></View></View></ScrollView>); }

// ── Theme Stories ──
export function ThemeStories() { return (<ScrollView style={{ padding: 20, backgroundColor: '#0A0A0A' }}><Text style={{ color: '#FFF', fontSize: 18, fontWeight: '700', marginBottom: 16 }}>Theme Modes</Text>{[{ mode: 'Light', bg: '#FFFFFF', text: '#111827' }, { mode: 'Dark', bg: '#1A1A2E', text: '#FFFFFF' }, { mode: 'AMOLED', bg: '#000000', text: '#FFFFFF' }].map(t => <View key={t.mode} style={{ marginBottom: 12, padding: 20, backgroundColor: t.bg, borderRadius: 16, borderWidth: 1, borderColor: '#2A2A3E' }}><Text style={{ color: t.text, fontWeight: '600' }}>{t.mode}</Text><View style={{ flexDirection: 'row', gap: 8, marginTop: 8 }}><View style={{ width: 24, height: 24, borderRadius: 6, backgroundColor: '#3B82F6' }} /><View style={{ width: 24, height: 24, borderRadius: 6, backgroundColor: '#10B981' }} /><View style={{ width: 24, height: 24, borderRadius: 6, backgroundColor: '#F59E0B' }} /><View style={{ width: 24, height: 24, borderRadius: 6, backgroundColor: '#EF4444' }} /></View></View>)}</ScrollView>); }