import React from 'react';
import { View, Text, TouchableOpacity, Modal, Pressable, StyleSheet } from 'react-native';
import { useTheme } from '../../theme'; import { radius } from '../../tokens';
export interface DialogProps { visible: boolean; onDismiss: () => void; title: string; message?: string; confirmLabel?: string; cancelLabel?: string; onConfirm?: () => void; variant?: 'default' | 'danger' | 'success'; loading?: boolean; children?: React.ReactNode; }
export const Dialog = ({ visible, onDismiss, title, message, confirmLabel = 'OK', cancelLabel = 'Cancel', onConfirm, variant = 'default', loading, children }: DialogProps) => {
  const { palette } = useTheme();
  const c = variant === 'danger' ? palette.danger[500] : variant === 'success' ? palette.success[500] : palette.primary[500];
  return (<Modal visible={visible} transparent animationType="fade" onRequestClose={onDismiss}><Pressable style={s.overlay} onPress={onDismiss}><Pressable style={[s.card, { backgroundColor: palette.surface.card }]}><Text style={[s.title, { color: palette.text.primary }]}>{title}</Text>{message && <Text style={[s.msg, { color: palette.text.secondary }]}>{message}</Text>}{children}<View style={s.actions}>{cancelLabel && <TouchableOpacity onPress={onDismiss} style={[s.btn, { backgroundColor: palette.surface.elevated }]}><Text style={{ color: palette.text.primary, fontWeight: '600', fontSize: 15 }}>{cancelLabel}</Text></TouchableOpacity>}{onConfirm && <TouchableOpacity onPress={onConfirm} disabled={loading} style={[s.btn, { backgroundColor: c, opacity: loading ? 0.6 : 1 }]}><Text style={{ color: '#FFF', fontWeight: '600', fontSize: 15 }}>{loading ? 'Loading...' : confirmLabel}</Text></TouchableOpacity>}</View></Pressable></Pressable></Modal>);
};
const s = StyleSheet.create({ overlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'center', alignItems: 'center', padding: 40 }, card: { width: '100%', maxWidth: 340, borderRadius: radius.lg, padding: 32 }, title: { fontSize: 18, fontWeight: '700', marginBottom: 8 }, msg: { fontSize: 14, lineHeight: 20, marginBottom: 20 }, actions: { flexDirection: 'row', gap: 12, justifyContent: 'flex-end' }, btn: { paddingVertical: 12, paddingHorizontal: 24, borderRadius: radius.md, alignItems: 'center' } });